<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SumathiLaptop" failures="1" tests="10" name="testNgTests.HomeTest" time="38.605" errors="0" timestamp="2025-03-06T21:50:02 CST" skipped="0">
  <testcase classname="testNgTests.HomeTest" name="Tree" time="1.899"/>
  <testcase classname="testNgTests.HomeTest" name="register" time="4.847"/>
  <testcase classname="testNgTests.HomeTest" name="DataStructure_DropDown" time="1.719">
    <failure message="expected [7] but found [6]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [7] but found [6]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at testNgTests.HomeTest.DataStructure_DropDown(HomeTest.java:92)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- DataStructure_DropDown -->
  <testcase classname="testNgTests.HomeTest" name="Queue" time="4.724"/>
  <testcase classname="testNgTests.HomeTest" name="Stack" time="5.068"/>
  <testcase classname="testNgTests.HomeTest" name="DS_Introduction" time="4.860"/>
  <testcase classname="testNgTests.HomeTest" name="Array" time="2.935"/>
  <testcase classname="testNgTests.HomeTest" name="graph" time="4.978"/>
  <testcase classname="testNgTests.HomeTest" name="Linked_List" time="1.890"/>
  <testcase classname="testNgTests.HomeTest" name="signIn" time="5.685"/>
</testsuite> <!-- testNgTests.HomeTest -->
